name: Build DestroyLobby

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Установить Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Собрать плагин
        run: mvn -B clean package

      - name: Собрать MediaTab (таб и скорборд)
        run: mvn -B -f mediatab/pom.xml clean package

      - name: Выложить jar
        uses: actions/upload-artifact@v4
        with:
          name: DestroyLobby
          path: target/*.jar

      - name: Выложить MediaTab
        uses: actions/upload-artifact@v4
        with:
          name: MediaTab
          path: mediatab/target/MediaTab.jar
